import { Quote } from "./types";

export const mockQuotes: Quote[] = [
  {
    id: "q-001",
    quoteNumber: "QM-2024-001",
    customer: {
      id: "c-001",
      name: "John Smith",
      email: "john.smith@example.co.nz",
      phone: "021 123 4567",
      address: "45 Kauri Road, Auckland 1010",
    },
    createdAt: "2024-12-01T10:30:00Z",
    status: "sent",
    lineItems: [
      {
        id: "li-001",
        description: "Replace kitchen tap - supply and install",
        quantity: 1,
        unitPrice: 280,
        type: "material",
      },
      {
        id: "li-002",
        description: "Fix leaking pipe under sink",
        quantity: 2,
        unitPrice: 95,
        type: "labour",
      },
      {
        id: "li-003",
        description: "Pipe fittings and materials",
        quantity: 1,
        unitPrice: 65,
        type: "material",
      },
    ],
    notes: "Customer requested early morning start time. Access via side gate.",
    subtotal: 535,
    gst: 80.25,
    total: 615.25,
  },
  {
    id: "q-002",
    quoteNumber: "QM-2024-002",
    customer: {
      id: "c-002",
      name: "ABC Building Ltd",
      email: "admin@abcbuilding.co.nz",
      phone: "09 555 1234",
      address: "Unit 3, 128 Great South Road, Wellington 6021",
    },
    createdAt: "2024-12-05T14:15:00Z",
    status: "draft",
    lineItems: [
      {
        id: "li-004",
        description: "Timber framing materials",
        quantity: 1,
        unitPrice: 3200,
        type: "material",
      },
      {
        id: "li-005",
        description: "Framing labour (2 days)",
        quantity: 16,
        unitPrice: 85,
        type: "labour",
      },
      {
        id: "li-006",
        description: "Gib board supply and installation",
        quantity: 1,
        unitPrice: 1850,
        type: "material",
      },
    ],
    notes: "Initial quote for garage conversion. Final measurements to be confirmed on-site.",
    subtotal: 6410,
    gst: 961.5,
    total: 7371.5,
  },
  {
    id: "q-003",
    quoteNumber: "QM-2024-003",
    customer: {
      id: "c-003",
      name: "Sarah Johnson",
      email: "sarah.j@email.com",
      phone: "027 987 6543",
      address: "22 Beach Road, Christchurch 8041",
    },
    createdAt: "2024-12-08T09:00:00Z",
    status: "accepted",
    lineItems: [
      {
        id: "li-007",
        description: "Exterior house painting - prep work",
        quantity: 1,
        unitPrice: 950,
        type: "labour",
      },
      {
        id: "li-008",
        description: "Premium exterior paint (100L)",
        quantity: 1,
        unitPrice: 680,
        type: "material",
      },
      {
        id: "li-009",
        description: "Painting labour (3 days)",
        quantity: 24,
        unitPrice: 75,
        type: "labour",
      },
    ],
    notes: "Weatherboard house, 3 bedrooms. Two-coat system with primer. Colour: Resene 'Alabaster'.",
    subtotal: 3430,
    gst: 514.5,
    total: 3944.5,
  },
];
